version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver
    ports:
      - "8000:8000"